default: true
MD003:
  style: setext_with_atx
MD004:
  style: sublist
MD013:
  line_length: 120
  tables: false
MD024:
  allow_different_nesting: true
MD029:
  style: ordered
MD033:
  allowed_elements:
  - br
