require: rubocop-performance

Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/LineLength:
  Max: 120

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Style/AsciiComments:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
