inherit_from: .rubocop_common.yml

require:
  - rubocop-rails
  - rubocop-minitest

Rails:
  Enabled: true
Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test
Metrics/BlockLength:
  Exclude:
    - config/routes/**/*
AllCops:
  TargetRubyVersion: 2.6
  # Do not exclude files from ALL COPS unless it's really necessary!
  Exclude:
    - app/**/constants.rb
    - app/serializers/**/*.rb
    - bin/**/*
    - tmp/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/environments/*.rb
    - config/routes.rb
    - node_modules/**/*
    - Vagrantfile
    - vendor/bundle/**/*
