docker: &docker
  docker:
    - image: circleci/ruby:2.5.1-node-browsers
      environment:
        TZ: '/usr/share/zoneinfo/Asia/Istanbul'
        RAILS_ENV: beta
        RACK_ENV: beta
        RDS_USERNAME: xokul
        RDS_PASSWORD: xokul
        RDS_HOSTNAME: localhost
        RDS_PORT: 5432
        BUNDLE_JOBS: 4
    - image: circleci/postgres:10.5-alpine
      environment:
        POSTGRES_DB: xokul_beta
        POSTGRES_USER: xokul
        POSTGRES_PASSWORD: xokul
version: 2
jobs:
  checkout_code:
    <<: *docker
    steps:
      - checkout
      - save_cache:
          key: xokul-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
  bundle_dependencies:
    <<: *docker
    steps:
      - restore_cache:
          key: xokul-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - xokul-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - xokul-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: xokul-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: xokul-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  karma:
    <<: *docker
    steps:
      - restore_cache:
          key: xokul-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - xokul-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - xokul-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Installing gems into bundle path
          command: bundle --path vendor/bundle
      - run:
          name: Running quality tasks
          command: bundle exec rake code:quality:all
      - run:
          name: Running security tasks
          command: bundle exec rake code:security:all
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy master branch to Dokku
          command: |
            git remote add beta dokku@app.omu.sh:xokul &&
            git push beta master
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - karma:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - karma
          filters:
            branches:
              only: master