docker: &docker
  docker:
    - image: circleci/ruby:2.5.3-node-browsers
      environment:
        TZ: '/usr/share/zoneinfo/Asia/Istanbul'
        RAILS_ENV: beta
        BUNDLE_JOBS: 4
    - image: circleci/postgres:10.5-alpine
      environment:
        POSTGRES_DB: xokul_beta
        POSTGRES_USER: xokul
        POSTGRES_PASSWORD: xokul
restore-repo: &restore-repo
  keys:
    - xokul-repo-{{ .Environment.CIRCLE_SHA1 }}
restore-bundle-dir: &restore-bundle-dir
  keys:
    - xokul-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
version: 2
jobs:
  checkout-code:
    <<: *docker
    steps:
      - checkout
      - save_cache:
          key: xokul-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
  bundle-dependencies:
    <<: *docker
    steps:
      - restore_cache: *restore-repo
      - restore_cache: *restore-bundle-dir
      - run:
          name: Installing dependencies via bundler
          command: bundle --path vendor/bundle --without development
      - save_cache:
          key: xokul-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  static-analysis:
    <<: *docker
    steps:
      - restore_cache: *restore-repo
      - restore_cache: *restore-bundle-dir
      - run: bundle --path vendor/bundle
      - run:
          name: Running static analysis checks
          command: bundle exec rake static_analysis:all
  deploy-master:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy master branch to Dokku
          command: |
            git remote add beta dokku@app.omu.sh:xokul &&
            git push beta master
  deploy-unstable:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy unstable branch to Dokku
          command: |
            git remote add beta dokku@app.omu.sh:xokul-unstable &&
            git push beta unstable:master
workflows:
  version: 2
  build:
    jobs:
      - checkout-code
      - bundle-dependencies:
          requires:
            - checkout-code
      - static-analysis:
          requires:
            - bundle-dependencies
      - deploy-master:
          requires:
            - static-analysis
          filters:
            branches:
              only: master
      - deploy-unstable:
          requires:
            - static-analysis
          filters:
            branches:
              only: unstable
